// src/components/palette/ColorItem.vue
<script setup lang="ts">
import { getContrastColor } from '~/utils/getConstrastColor'
import { hexColorToRgb } from '~/utils/hexColorToRgb'
import { options } from '~/state/options'
import { FzfColor } from '~/types/fzf'
import { computed } from 'vue'

const props = defineProps<{ token: FzfColor }>()

const toFzfName = (name: string) => {
  return name.replace('-plus', '+')
}

const getColorValue = (color: string) => {
  if (color.startsWith('#')) {
    return color
  }

  const matches = color.match(/var\(--fzf-([a-z-]+)\)/)
  if (matches && matches[1]) {
    return `same as ${toFzfName(matches[1])}`
  }

  return ''
}

const contrastColor = computed(() => getContrastColor(options.colors[props.token]))
const contrastRgb = computed(() =>
  hexColorToRgb(contrastColor.value === 'dark' ? '#dddddd' : '#ffffff'),
)
</script>

<template>
  <div class="wrapper">
    <button
      class="color"
      :class="{ selected: options.selectedColor === token }"
      :style="{
        'backgroundColor': options.colors[token],
        'color': contrastColor === 'dark' ? '#000' : '#fff',
        '--border-color-hover': `rgba(${contrastRgb?.r}, ${contrastRgb?.g}, ${contrastRgb?.b}, .8)`,
      }"
      @click="options.selectedColor = props.token"
    >
      <div class="name">{{ toFzfName(token) }}</div>
      <div class="hex">{{ getColorValue(options.colors[props.token]) }}</div>
    </button>
  </div>
</template>

<style scoped>
.wrapper {
  padding: 3px;
}

.color {
  display: flex;
  text-align: center;
  flex-direction: column;
  gap: 6px;
  width: 100%;
  /* height: 80px; */
  position: relative;
  justify-content: space-between;
  cursor: pointer;
  padding: 10px 6px 6px;
  border-radius: 0;
  border: 0;
  transition: none;

  outline: 3px solid transparent;

  &.selected,
  &:focus,
  &:hover,
  &:focus {
    outline: 3px solid var(--border-color-hover);
    border: 0;
  }

  .name {
    font-size: 20px;
    font-weight: bold;
    opacity: 0.7;
  }

  .hex {
    font-size: 1rem;
    opacity: 0.7;
  }

  input {
    width: 0;
    height: 0;
    visibility: hidden;
    pointer-events: none;
    position: absolute;
    bottom: 0;
  }
}
</style>

// src/components/palette/ColorItem.svelte
<script lang="ts">
  import { hexColorToRgb } from '~/utils/hexColorToRgb';
  import type { FzfColor } from '~/types/fzf';
  import { getContrastColor } from '~/utils/getContrastColor';
  import { getColorOrFallback, colorsStore } from '~/data/colorsStore';
  import { colorDefinitions } from '~/data/fzfDefinitions';

  export let token: FzfColor;

  const toFzfName = (name: string) => {
    return name.replace('-plus', '+');
  };

  const getColorLabel = (color: string) => {
    if (color.startsWith('#')) {
      return color;
    }

    if (!color && colorDefinitions[token].inherits) {
      return 'inherit';
    }

    return '---';
  };

  $: color = getColorOrFallback(token, $colorsStore.colors).value;
  $: contrastColor = getContrastColor(color);
  $: borderColor = hexColorToRgb(contrastColor === 'dark' ? '#dddddd' : '#ffffff');
</script>

<div class="wrapper">
  <button
    type="button"
    class="color"
    class:selected={$colorsStore.selectedColor === token}
    style:color={contrastColor === 'dark' ? '#000' : '#fff'}
    style:background-color={color}
    style:--border-color-hover={`rgba(${borderColor?.r}, ${borderColor?.g}, ${borderColor?.b}, .8)`}
    on:click={void colorsStore.setSelected(token)}
  >
    <div class="name"><span>{toFzfName(token)}</span></div>
    <div class="hex">{getColorLabel($colorsStore.colors[token])}</div>
  </button>
</div>

<style lang="scss">
  .wrapper {
    padding: 3px;
  }

  .color {
    display: flex;
    flex-direction: column;
    gap: 6px;
    width: 100%;
    height: 70px;
    position: relative;
    justify-content: space-between;
    align-items: center;
    cursor: pointer;
    padding: 8px 4px 4px;
    border-radius: 0;
    border: 0;
    transition: none;

    outline: 3px solid transparent;

    &.selected,
    &:hover {
      outline: 3px solid var(--border-color-hover);
      border: 0;
    }

    .name {
      font-size: 16px;
      text-transform: uppercase;
      font-weight: bold;
      opacity: 0.7;
      flex: 1;
      display: flex;
      align-items: center;
    }

    .hex {
      font-size: 1rem;
      flex: 0;
      opacity: 0.7;
    }
  }
</style>
